<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.simbest.cloud</groupId>
        <artifactId>simbest-cloud-parent</artifactId>
        <version>1.0</version>
    </parent>

	<groupId>com.simbest.cloud</groupId>
    <artifactId>simbest-cloud-cores</artifactId>
    <packaging>jar</packaging>
	<version>${simbest.cloud.version}</version>

    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>${java.version}</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.simbest.boot</groupId>
            <artifactId>simbest-boot-orguser</artifactId>
            <version>${simbest.boot.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>releases</id>
            <url>http://10.87.57.26:8082/nexus/repository/releases/</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </releases>
        </repository>
        <repository>
            <id>maven-thirdparty</id>
            <url>http://10.87.57.26:8082/nexus/repository/maven-thirdparty/</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </releases>
        </repository>
    </repositories>

    <distributionManagement>
        <repository>
            <id>releases</id>
            <url>http://10.87.57.26:8082/nexus/repository/releases/</url>
        </repository>
        <snapshotRepository>
            <id>maven-snapshots</id>
            <url>http://10.87.57.26:8082/nexus/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>
</project>