@echo begin deploy..............................
set JAVA_HOME=C:\Java\graalvm-jdk-17.0.9+11.1
call mvn clean deploy -U -Dmaven.test.skip=true
@echo deploy finished..............................
pause